AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - com.billogram.evaluation.pebjorkstad::discount-code-manager
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  DiscountCodeManagerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.billogram.evaluation.pebjorkstad.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: .
      MemorySize: 512
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Timeout: 30
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  DiscountCodeManagerApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: DiscountCodeManagerApi
